"""Large-scale VRP research utilities for neuro-co."""

from .benchmark import (
    BenchmarkGridConfig,
    PartitionBaselineConfig,
    iter_benchmark_records,
    write_benchmark_jsonl,
)
from .cluster_encoder import ClusterLocalEncoder
from .compatibility import (
    CompatibilityWeights,
    pairwise_feature_distance,
    routing_compatibility_distance_matrix,
    routing_compatibility_score_matrix,
)
from .compose import (
    actions_from_solution,
    compose_nearest_neighbor,
    compose_time_window_aware,
    nearest_neighbor_route,
    time_window_aware_routes,
)
from .datasets import (
    core_state_to_instance,
    sample_clustered_instances,
    sample_core_instances,
)
from .decode import (
    ActionSetBuilder,
    BatchedRollout,
    ClusterActionSet,
    ClusterAwareEncoder,
    DecodeMode,
    HierarchicalPolicy,
    HierarchicalRollout,
    LocalPointer,
    NeighborhoodActionSet,
    NodeEncoder,
    build_instance_features,
    hierarchical_rollout,
    hierarchical_rollout_batched,
)
from .eval import (
    MethodEval,
    PairedGap,
    evaluate_constructor,
    evaluate_policy,
    evaluate_pyvrp,
    paired_gap,
)
from .features import FeatureConfig, client_feature_matrix, time_horizon
from .hierarchical import (
    ClusterIndex,
    ClusterSelectionMode,
    ClusterSelector,
    LinearClusterSelector,
    SelectedClusterActionSet,
    active_cluster_mask,
    aggregate_cluster_embeddings,
    build_cluster_index,
    cluster_log_prob,
    gather_neighborhood_action_set,
    gather_selected_cluster_action_set,
    mask_cluster_logits,
    scatter_local_logits,
    select_cluster,
)
from .local import (
    LocalSubproblem,
    extract_local_subproblem,
    iter_local_subproblems,
    merge_local_solutions,
)
from .metrics import evaluate_solution, solution_cost
from .partition import (
    capacity_aware_sweep_partition,
    feature_aware_partition,
    grid_partition,
    morton_order,
    morton_partition,
    morton_refined_partition,
    sweep_partition,
)
from .partition_metrics import evaluate_partition
from .train import TrainConfig, TrainStep, reinforce_loss, train_hierarchical
from .types import Partition, PartitionQualityMetrics, ScaleMetrics, Solution, VRPInstance

__all__ = [
    "ActionSetBuilder",
    "BatchedRollout",
    "BenchmarkGridConfig",
    "ClusterActionSet",
    "ClusterAwareEncoder",
    "ClusterIndex",
    "ClusterLocalEncoder",
    "ClusterSelectionMode",
    "ClusterSelector",
    "CompatibilityWeights",
    "DecodeMode",
    "FeatureConfig",
    "HierarchicalPolicy",
    "HierarchicalRollout",
    "LinearClusterSelector",
    "LocalPointer",
    "LocalSubproblem",
    "MethodEval",
    "NeighborhoodActionSet",
    "NodeEncoder",
    "PairedGap",
    "Partition",
    "PartitionBaselineConfig",
    "PartitionQualityMetrics",
    "ScaleMetrics",
    "SelectedClusterActionSet",
    "Solution",
    "TrainConfig",
    "TrainStep",
    "VRPInstance",
    "actions_from_solution",
    "active_cluster_mask",
    "aggregate_cluster_embeddings",
    "build_cluster_index",
    "build_instance_features",
    "capacity_aware_sweep_partition",
    "client_feature_matrix",
    "cluster_log_prob",
    "compose_nearest_neighbor",
    "compose_time_window_aware",
    "core_state_to_instance",
    "evaluate_constructor",
    "evaluate_partition",
    "evaluate_policy",
    "evaluate_pyvrp",
    "evaluate_solution",
    "extract_local_subproblem",
    "feature_aware_partition",
    "gather_neighborhood_action_set",
    "gather_selected_cluster_action_set",
    "grid_partition",
    "hierarchical_rollout",
    "hierarchical_rollout_batched",
    "iter_benchmark_records",
    "iter_local_subproblems",
    "mask_cluster_logits",
    "merge_local_solutions",
    "morton_order",
    "morton_partition",
    "morton_refined_partition",
    "nearest_neighbor_route",
    "paired_gap",
    "pairwise_feature_distance",
    "reinforce_loss",
    "routing_compatibility_distance_matrix",
    "routing_compatibility_score_matrix",
    "sample_clustered_instances",
    "sample_core_instances",
    "scatter_local_logits",
    "select_cluster",
    "solution_cost",
    "sweep_partition",
    "time_horizon",
    "time_window_aware_routes",
    "train_hierarchical",
    "write_benchmark_jsonl",
]
